<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-7VN3JM0R" failures="2" tests="2" name="CucumberTestRunner.TestRunner" time="9.285" errors="0" timestamp="2024-05-08T16:08:24 IST" skipped="0">
  <testcase classname="CucumberTestRunner.TestRunner" name="runScenario" time="0.513">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at stepDefinitions.AddPlaceStepDefinitions.user_calls_with_http_request(AddPlaceStepDefinitions.java:89)
at stepDefinitions.AddPlaceStepDefinitions.verify_place_id_created_maps_to_using(AddPlaceStepDefinitions.java:152)
at ✽.verify place_Id created maps to "Dhanaji" using "getPlaceAPI"(file:///D:/AutomationCode/RESTAPICucumberFramework/src/test/java/Features/AddPlacePune.feature:10)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="CucumberTestRunner.TestRunner" name="runScenario" time="8.772">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at stepDefinitions.AddPlaceStepDefinitions.user_calls_with_http_request(AddPlaceStepDefinitions.java:89)
at stepDefinitions.AddPlaceStepDefinitions.verify_place_id_created_maps_to_using(AddPlaceStepDefinitions.java:152)
at ✽.verify place_Id created maps to "Habanhouse" using "getPlaceAPI"(file:///D:/AutomationCode/RESTAPICucumberFramework/src/test/java/Features/AddPlace.feature:10)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- CucumberTestRunner.TestRunner -->
